def build(bld) :
    uses = ['bob/connect/game']
    libs = []
    parent_name = 'bob/connect/game'

    bld.create_boost_test(uses, libs, parent_name, 'win_condition01')
    bld.create_boost_test(uses, libs, parent_name, 'win_condition02')

