def build(bld) :
    bld( features = 'cxx cxxprogram'
       , target = 'bob_connect_server'
       , source = 'game_server.cpp game_session.cpp main.cpp'
       , includes = '../../../'
       , use = ['bob/database', 'bob/connect/game']
       , lib = ['sqlite3', 'boost_system', 'boost_thread', 'pthread']
       )
