def build(bld) :
    bld( features = 'cxx cxxstlib'
       , target = 'bob/connect/game'
       , source = 'board.cpp'
       , includes = '../../../'
       , export_includes = '../../../'
       , use = []
       , lib = []
       )
       
    bld.recurse('tests')
